### ISSUE TITLE
Can't use Claim rewards button

### ISSUE THREAD

**Issue by SuperRenzi** [Waurum-Studio/waurum-issues#17]
### Expected Behavior

Be able to clicl the button

### Actual Behavior

Not being able to click the button

### Reproduction Steps

```markdown
1. Open the Refferal Rewards pannel F7/M
2. Reffer a player and the player accepting the reffer
3. Hoping that the button won't work
```

### Concerned Platform(s)

[GMOD]  Pedobear Server

### Version

v2022.703.0

### Console Error

No

### Additional Information

No

**Comment by dotCore-off** [comment]
Fixed
