### ISSUE TITLE
Buttons equip/uneqip from F4 not dissapearing after closing the F4 menu

### ISSUE THREAD

**Issue by SuperRenzi** [Waurum-Studio/waurum-issues#18]
### Expected Behavior

When clicking on an item in the inventory, the button uneqip/equip dissapeares after closing the F4 menu.

### Actual Behavior

When clicking on an item in the inventory, the button uneqip/equip don't dissapear even after closing the F4 menu and they continue staying on the screen.

### Reproduction Steps

```markdown
1. Open the F4 menu
2. CLick on an item in your inventory
3. Hope that when closing the F4 menu the button equip/uneqip stay on the screeen
```

### Concerned Platform(s)

[GMOD]  Pedobear Server

### Version

v2022.703.0

### Console Error

No

### Additional Information

No

**Comment by dotCore-off** [comment]
Fixed.
