### ISSUE TITLE
Being able to also claim the daily reward from a previus day

### ISSUE THREAD

**Issue by SuperRenzi** [Waurum-Studio/waurum-issues#19]
### Expected Behavior

When logging in the server and claiming your daily reward to be able to claim only the reward for this day

### Actual Behavior

When logging in the server and claiming the daily reward being able to also claim the daily reward from a previus day.

### Reproduction Steps

```markdown
1. Log in the server when the rewards for the next day have arrived
2. Go to the rewards Pannel F7/M
3. Hope that you will be able to claim the rewards from a previous day
```

### Concerned Platform(s)

[GMOD]  Pedobear Server

### Version

v2022.703.0

### Console Error

No

### Additional Information

No

**Comment by dotCore-off** [comment]
Fixed, ~~probably~~.
