### ISSUE TITLE
Be able to block people

### ISSUE THREAD

**Issue by Gudmund1203** [Waurum-Studio/waurum-issues#29]
### Description

If a guy keeps bypassing a mute with !pm and spams me, it would be cool if I could remove it from my eyes like with !mute but just !mutepms, nuts.

### Concerned Platform(s)

[GMOD]  Pedobear Server

**Comment by dotCore-off** [comment]
Really sweet feature I'll definitely add one of these days.
Gotta think about how to UI it and if SUI have a render function that can also fetch offline players by SteamID64 for example.
As for the saving, gotta see if I can implement it in SCB settings system or not.

As for the concept, either:
- player won't be able to target you with !pm if you blocked him
- player messages won't be shown in the chat if you blocked him
- player messages will appear as "New message from blocked person" (like Discord does)

For now, I'll update !pm to disable it in case the player is affected by a mute.

**Comment by dotCore-off** [comment]
Completed original request.
